### ISSUE TITLE
document RidgeSolver() params

### ISSUE THREAD

**Issue by malykhin-yuri** [TZZZZ/new_ridge_no_curse#1]
https://github.com/TZZZZ/new_ridge_no_curse/blob/9d9cc0ce68b5cb545267a3a8849a26aaeb77d7c6/ridge_algorithm.py#L59

поскольку параметры M,N,... являются обязательными, нужно прописать в docstring-е их смысл
типа, M -- degree of fitting polynomials

хорошо бы научиться задавать разумные дефолты, оставив обязательными пару параметров; например, N = 2*M^2 (из теории) или что-то такое

**Comment by TZZZZ** [comment]
done
