### ISSUE TITLE
make get_random_unit_vector module-level

### ISSUE THREAD

**Issue by malykhin-yuri** [TZZZZ/new_ridge_no_curse#2]
https://github.com/TZZZZ/new_ridge_no_curse/blob/9d9cc0ce68b5cb545267a3a8849a26aaeb77d7c6/ridge_algorithm.py#L74

предлагаю вынести функцию получения случайного вектора на уровень модуля, чтобы использовать её в тесте

**Comment by TZZZZ** [comment]
done
